version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - nm-{{ checksum "package-lock.json" }}
            - nm- # used if checksum fails
      - run: npm install
      - save_cache:
          key: nm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm run test:coverage
      - store_artifacts:
          path: coverage
